# Generated by Django 2.2.3 on 2019-10-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
