# Generated by Django 2.2.3 on 2019-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.SmallIntegerField(),
        ),
    ]
