# Generated by Django 2.1 on 2019-10-18 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
